### ISSUE TITLE
UI文字修正：脚注→メモ (每個順番寫註解的model)

### ISSUE THREAD

**Issue by JohnsonChung** [PSEJP/junban-handheld#2]
![-1](https://cloud.githubusercontent.com/assets/4928770/15634289/d79c5fc2-25f2-11e6-8428-294f5eab3a99.jpg)

**Comment by touhonoob** [comment]
closed by 
https://github.com/touhonoob/junban-concierge.com/commit/b2924912df93d38ca822ccd717870b431839fd31
